### ISSUE TITLE
Unable to import Display in hardware_setup.py - Close this - I figured it out.

### ISSUE THREAD

**Issue by adrianblakey** [peterhinch/micropython-micro-gui#51]
Any ideas why the import fails?

The error message is caused by a circular import ...

Running this hardware_setup.py
```
from machine import Pin, SPI
import gc

from drivers.st7789.st7789_4bit import *
SSD = ST7789
gc.collect()
spi = SPI(1, 30_000_000, sck=Pin(10), mosi=Pin(11), miso=None)
pcs = Pin(9, Pin.OUT, value=1)
prst = Pin(12, Pin.OUT, value=1)
pbl = Pin(13, Pin.OUT, value=1)
pdc = Pin(8, Pin.OUT, value=0)
ssd = SSD(spi, height=135, width=240, dc=pdc, cs=pcs, rst=prst, disp_mode=LANDSCAPE, display=TDISPLAY)

from gui.core.ugui import Display, quiet


key_a = Pin(15,Pin.IN,Pin.PULL_UP)
key_b = Pin(17,Pin.IN,Pin.PULL_UP)

key_up    = Pin(2 ,Pin.IN,Pin.PULL_UP)
key_enter = Pin(3 ,Pin.IN,Pin.PULL_UP)
key_left  = Pin(16 ,Pin.IN,Pin.PULL_UP)
key_down  = Pin(18 ,Pin.IN,Pin.PULL_UP)
key_right = Pin(20 ,Pin.IN,Pin.PULL_UP)

display = Display(ssd, key_right, key_enter, key_left, key_b, key_a)
```

Returns this: 
```
Traceback (most recent call last):
  File "<stdin>", line 24, in <module>
  File "/lib/gui/core/ugui.py", line 16, in <module>
  File "/lib/gui/core/colors.py", line 5, in <module>
  File "hardware_setup.py", line 24, in <module>
ImportError: can't import name Display
```
Note: ssd is instantiated without error and is available as ssd in the Display constructor.

Running this from the REPL:
```
import gui.core.ugui
```

Same error - because colors.py imports hardware_setup ...
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/gui/core/ugui.py", line 16, in <module>
  File "/lib/gui/core/colors.py", line 5, in <module>
  File "hardware_setup.py", line 24, in <module>
ImportError: can't import name Display
```

**Comment by peterhinch** [comment]
I suggest you install and run one of the demos. This is the most minimal:
```py
>>> import gui.demos.simple
```
This should run if the directory structure is correct. Then base your application initiation on the demo script.
