### ISSUE TITLE
pushbutton not in main

### ISSUE THREAD

**Issue by bartcerneels** [peterhinch/micropython-micro-gui#9]
I've tried to rebase my custom branch to main but it seems a file is missing?
Unless I'm mistaken and it's supposed to use something included in uP's extmod/uasyncio?

```
>>> import gui.demos.slider
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gui/demos/slider.py", line 7, in <module>
  File "hardware_setup.py", line 23, in <module>
  File "gui/core/ugui.py", line 16, in <module>
  File "gui/primitives/__init__.py", line 20, in __getattr__
ImportError: no module named 'gui.primitives.pushbutton'
```

**Comment by peterhinch** [comment]
Apologies and thanks for the report - I forgot to do a `git add`. It's now pushed.
